name: publish package

on:
  push:
    tags:
      - '*'
    tags-ignore:
      - v*

jobs:
  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2'

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install poetry
        uses: Gr1N/setup-poetry@v7

      - name: set package version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: build terms
        run: |
          make install
          make release
